name: medilab_prokit
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
#  google_maps_flutter: ^2.2.7
  google_maps_flutter: ^2.1.5
  flutter_neumorphic: ^3.0.3
  cached_network_image: ^3.2.0
  awesome_dialog: ^2.1.3
  image_picker: ^0.8.5
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  # Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  # Google Map
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.0.5
  geocoding: ^2.0.4

  # Firebase And Notification
#  firebase_messaging: ^11.2.7
#  firebase_core: ^1.12.0
  fl_chart: ^0.62.0
  provider: ^6.0.5
  flutter_svg: ^1.0.0
  flutter_local_notifications: ^9.5.3+1
#  cloud_firestore: ^3.1.9
  # Local Data Cache
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0
  # Qrcode
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  grouped_list: ^4.2.0
  url_launcher: ^6.1.2
  dropdown_search: ^3.0.1
  badges: ^2.0.2
  http: ^0.13.4
  flutter_sequence_animation: ^2.0.0
  flutter_carousel_slider: ^1.0.2
  # Base
  cupertino_icons: ^1.0.4

  nb_utils: ^4.4.10
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.2.0
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0
  country_code_picker: 2.0.2
  percent_indicator: ^3.0.1
  otp_text_field: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7
  path_provider: ^2.0.2

  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/

