// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaT5N4C2twEITLzSh78Cx_VndEkxnu5z8',
    appId: '1:1060793526360:web:928329c8af338aaf0e822d',
    messagingSenderId: '1060793526360',
    projectId: 'jurly-is-so-cool',
    authDomain: 'jurly-is-so-cool.firebaseapp.com',
    storageBucket: 'jurly-is-so-cool.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sdMG-YIfvOiG9RnLPlfa1xHLTuSe5CU',
    appId: '1:1060793526360:android:209776e85d26cd6b0e822d',
    messagingSenderId: '1060793526360',
    projectId: 'jurly-is-so-cool',
    storageBucket: 'jurly-is-so-cool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq3hWTZ02JEOrGn6uLZztul4_rDf-t-Jg',
    appId: '1:1060793526360:ios:10eb1a198473d2030e822d',
    messagingSenderId: '1060793526360',
    projectId: 'jurly-is-so-cool',
    storageBucket: 'jurly-is-so-cool.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo',
  );
}
